name: torch_tabular
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _py-xgboost-mutex=2.0=gpu_0
  - absl-py=2.1.0=pyhd8ed1ab_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - aws-c-auth=0.7.31=hce3b56f_0
  - aws-c-cal=0.7.4=hf1fc857_1
  - aws-c-common=0.9.28=h2466b09_0
  - aws-c-compression=0.2.19=hf1fc857_1
  - aws-c-event-stream=0.4.3=hd0ca3c1_2
  - aws-c-http=0.8.10=heca9ddf_0
  - aws-c-io=0.14.18=h3831a8d_10
  - aws-c-mqtt=0.10.6=hf27581b_0
  - aws-c-s3=0.6.6=h56e9fbd_0
  - aws-c-sdkutils=0.1.19=hf1fc857_3
  - aws-checksums=0.1.20=hf1fc857_0
  - aws-crt-cpp=0.28.3=hd65be8e_5
  - aws-sdk-cpp=1.11.407=h25dd3c2_0
  - blas=2.122=mkl
  - blas-devel=3.9.0=22_win64_mkl
  - brotli=1.1.0=hcfcfb64_1
  - brotli-bin=1.1.0=hcfcfb64_1
  - brotli-python=1.1.0=py310h00ffb61_1
  - bzip2=1.0.8=hcfcfb64_5
  - c-ares=1.28.1=hcfcfb64_0
  - ca-certificates=2024.8.30=h56e8100_0
  - category_encoders=2.6.3=pyhd8ed1ab_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=win_pyh7428d3b_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.1=py310h232114e_0
  - cuda-cccl=12.4.127=0
  - cuda-cudart=11.7.99=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-libraries-dev=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvrtc-dev=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cuda-version=12.6=h7480c83_3
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.1=py310h00ffb61_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - einops=0.7.0=pyhd8ed1ab_1
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - fonttools=4.51.0=py310h8d17308_0
  - freetype=2.12.1=hdaf720e_2
  - fsspec=2024.3.1=pyhca7485f_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - grpcio=1.62.2=py310hb84602e_0
  - idna=3.7=pyhd8ed1ab_0
  - imbalanced-learn=0.12.3=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib-resources=6.4.0=pyhd8ed1ab_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - intel-openmp=2024.1.0=h57928b3_965
  - ipykernel=6.29.3=pyha63f2e9_0
  - ipython=8.22.2=pyh7428d3b_0
  - ipywidgets=8.1.2=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=hcfcfb64_3
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py310h5588dad_0
  - jupyterlab_widgets=3.0.10=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py310h232114e_1
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.15=ha5c8aab_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20240116.2=cxx17_h63175ca_0
  - libarrow=17.0.0=h5bcb882_16_cpu
  - libarrow-acero=17.0.0=he0c23c2_16_cpu
  - libarrow-dataset=17.0.0=he0c23c2_16_cpu
  - libarrow-substrait=17.0.0=h1f0e801_16_cpu
  - libblas=3.9.0=22_win64_mkl
  - libbrotlicommon=1.1.0=hcfcfb64_1
  - libbrotlidec=1.1.0=hcfcfb64_1
  - libbrotlienc=1.1.0=hcfcfb64_1
  - libcblas=3.9.0=22_win64_mkl
  - libcrc32c=1.1.2=h0e60522_0
  - libcublas=11.10.3.66=0
  - libcublas-dev=11.10.3.66=0
  - libcufft=10.7.2.124=0
  - libcufft-dev=10.7.2.124=0
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcurl=8.10.1=h1ee3ff0_0
  - libcusolver=11.4.0.1=0
  - libcusolver-dev=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libcusparse-dev=11.7.4.91=0
  - libdeflate=1.17=hcfcfb64_0
  - libevent=2.1.12=h3671451_1
  - libffi=3.4.2=h8ffe710_5
  - libgoogle-cloud=2.29.0=h5e7cea3_0
  - libgoogle-cloud-storage=2.29.0=he5eb982_0
  - libgrpc=1.62.2=h5273850_0
  - libhwloc=2.10.0=default_h2fffb23_1000
  - libiconv=1.17=hcfcfb64_2
  - liblapack=3.9.0=22_win64_mkl
  - liblapacke=3.9.0=22_win64_mkl
  - libnpp=11.7.4.75=0
  - libnpp-dev=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libnvjpeg-dev=11.8.0.2=0
  - libparquet=17.0.0=ha915800_16_cpu
  - libpng=1.6.44=h3ca93ac_0
  - libprotobuf=4.25.3=h47a098d_1
  - libre2-11=2023.09.01=hf8d8778_2
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.45.3=hcfcfb64_0
  - libssh2=1.11.0=h7dfc565_0
  - libthrift=0.20.0=hbe90ef8_1
  - libtiff=4.5.0=hf8721a0_2
  - libutf8proc=2.8.0=h82a8f57_0
  - libuv=1.48.0=hcfcfb64_0
  - libwebp-base=1.4.0=hcfcfb64_0
  - libxcb=1.13=hcd874cb_1004
  - libxgboost=2.1.1=cuda120_he04f013_4
  - libxml2=2.12.7=h0f24e4e_4
  - libzlib=1.3.1=h2466b09_1
  - lightning-utilities=0.11.2=pyhd8ed1ab_0
  - lz4-c=1.9.4=hcfcfb64_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py310h8d17308_0
  - matplotlib-base=3.8.4=py310hc9baf74_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mkl=2024.1.0=h66d3029_692
  - mkl-devel=2024.1.0=h57928b3_692
  - mkl-include=2024.1.0=h66d3029_692
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=1.26.4=py310hf667824_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - onnx=1.16.0=py310ha9b47f1_0
  - openjpeg=2.5.0=ha2aaf27_2
  - openssl=3.3.2=h2466b09_0
  - orc=2.0.2=h784c2ca_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.2=py310hecd3228_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - patsy=0.5.6=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py310hdbb7713_1
  - pip=24.0=pyhd8ed1ab_0
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - protobuf=4.25.3=py310hf536535_0
  - psutil=5.9.8=py310h8d17308_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-xgboost=2.1.1=cuda120_pyh206be00_4
  - pyarrow=17.0.0=py310h05ea346_1
  - pyarrow-core=17.0.0=py310h399dd74_1_cpu
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.10.14=h4de0772_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytorch=1.13.1=py3.10_cuda11.7_cudnn8_0
  - pytorch-cuda=11.7=h16d0643_5
  - pytorch-lightning=2.1.4=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytorch-tabnet=4.1.0=pyhd8ed1ab_0
  - pytorch_tabular=1.1.0=pyha770c72_0
  - pytz=2024.1=pyhd8ed1ab_0
  - pywin32=306=py310h00ffb61_2
  - pyyaml=6.0.1=py310h8d17308_1
  - pyzmq=26.0.2=py310h656833d_0
  - re2=2023.09.01=hd3b24a8_2
  - requests=2.31.0=pyhd8ed1ab_0
  - rich=13.7.1=pyhd8ed1ab_0
  - scikit-learn=1.4.2=py310hfd2573f_0
  - scipy=1.13.0=py310h46043a1_1
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - sentry-sdk=2.0.1=pyhd8ed1ab_0
  - setproctitle=1.3.3=py310h8d17308_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.2.1=h23299a8_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.1=py310h3e78b6c_0
  - tbb=2021.12.0=h91493d7_0
  - tensorboard=2.16.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py310h5588dad_1
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=h5226925_1
  - torchmetrics=1.2.1=pyhd8ed1ab_0
  - tornado=6.4=py310h8d17308_0
  - tqdm=4.66.4=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=15.1.0=py310h8d17308_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - vc=14.3=hcf57466_18
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - wandb=0.16.5=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - werkzeug=3.0.2=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - widgetsnbextension=4.0.10=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xgboost=2.1.1=cuda120_pyh993ee4f_4
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.5=he0c23c2_3
  - zipp=3.17.0=pyhd8ed1ab_0
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - pytorch-optimizer==2.12.0
      - torchaudio==0.13.1
      - torchvision==0.14.1
prefix: C:\Users\egeorge1\.conda\envs\torch_tabular
