name: tsai
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - alembic=1.13.2=pyhd8ed1ab_0
  - anyio=4.4.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py312h4389bb4_5
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - aws-c-auth=0.7.31=hce3b56f_0
  - aws-c-cal=0.7.4=hf1fc857_1
  - aws-c-common=0.9.28=h2466b09_0
  - aws-c-compression=0.2.19=hf1fc857_1
  - aws-c-event-stream=0.4.3=hd0ca3c1_2
  - aws-c-http=0.8.10=heca9ddf_0
  - aws-c-io=0.14.18=h3831a8d_10
  - aws-c-mqtt=0.10.6=hf27581b_0
  - aws-c-s3=0.6.6=h56e9fbd_0
  - aws-c-sdkutils=0.1.19=hf1fc857_3
  - aws-checksums=0.1.20=hf1fc857_0
  - aws-crt-cpp=0.28.3=hd65be8e_5
  - aws-sdk-cpp=1.11.407=h25dd3c2_0
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - blas=1.0=mkl
  - bleach=6.1.0=pyhd8ed1ab_0
  - bokeh=3.5.2=pyhd8ed1ab_0
  - brotli-python=1.1.0=py312h275cf98_2
  - bzip2=1.0.8=h2466b09_7
  - c-ares=1.33.1=h2466b09_0
  - ca-certificates=2024.8.30=h56e8100_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py312h4389bb4_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=win_pyh7428d3b_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorlog=6.8.2=py312h2e8e312_1
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.3.0=py312hd5eb7cc_2
  - cuda-cccl=12.6.37=0
  - cuda-cccl_win-64=12.6.37=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.68=0
  - cuda-opencl-dev=12.6.68=0
  - cuda-profiler-api=12.6.68=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - cytoolz=0.12.3=py312he70551f_0
  - dask=2024.9.0=pyhd8ed1ab_0
  - dask-core=2024.9.0=pyhd8ed1ab_0
  - dask-expr=1.1.14=pyhd8ed1ab_0
  - debugpy=1.8.5=py312h275cf98_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distributed=2024.9.0=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - filelock=3.16.1=pyhd8ed1ab_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=hdaf720e_2
  - fsspec=2024.9.0=pyhff2d567_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - greenlet=3.1.1=py312h275cf98_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.5=pyhd8ed1ab_0
  - httpx=0.27.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.27.0=pyh7428d3b_0
  - ipywidgets=8.1.5=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py312h2e8e312_1
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_0
  - jupyter=1.1.1=pyhd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312h2e8e312_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.2.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=h67d730c_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20240116.2=cxx17_he0c23c2_1
  - libarrow=17.0.0=h5bcb882_16_cpu
  - libarrow-acero=17.0.0=he0c23c2_16_cpu
  - libarrow-dataset=17.0.0=he0c23c2_16_cpu
  - libarrow-substrait=17.0.0=h1f0e801_16_cpu
  - libblas=3.9.0=1_h8933c1f_netlib
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcblas=3.9.0=5_hd5c7e75_netlib
  - libcrc32c=1.1.2=h0e60522_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.7.68=0
  - libcurand-dev=10.3.7.68=0
  - libcurl=8.10.1=h1ee3ff0_0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.21=h2466b09_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.6.3=he0c23c2_0
  - libffi=3.4.2=h8ffe710_5
  - libgoogle-cloud=2.29.0=h5e7cea3_0
  - libgoogle-cloud-storage=2.29.0=he5eb982_0
  - libgrpc=1.62.2=h5273850_0
  - libhwloc=2.11.1=default_h8125262_1000
  - libiconv=1.17=hcfcfb64_2
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - liblapack=3.9.0=5_hd5c7e75_netlib
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libparquet=17.0.0=ha915800_16_cpu
  - libpng=1.6.44=h3ca93ac_0
  - libprotobuf=4.25.3=h503648d_0
  - libre2-11=2023.09.01=hf8d8778_2
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.46.1=h2466b09_0
  - libssh2=1.11.0=h7dfc565_0
  - libthrift=0.20.0=hbe90ef8_1
  - libtiff=4.6.0=hb151862_4
  - libutf8proc=2.8.0=h82a8f57_0
  - libuv=1.48.0=hcfcfb64_0
  - libwebp-base=1.4.0=hcfcfb64_0
  - libxcb=1.16=h013a479_1
  - libxml2=2.12.7=h0f24e4e_4
  - libzlib=1.3.1=h2466b09_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py312h0608a1d_1
  - lz4-c=1.9.4=hcfcfb64_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mako=1.3.5=pyhd8ed1ab_0
  - markupsafe=2.1.5=py312h4389bb4_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mkl=2024.2.1=h66d3029_102
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msgpack-python=1.1.0=py312hd5eb7cc_0
  - msys2-conda-epoch=20160418=1
  - natsort=8.4.0=pyhd8ed1ab_0
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.3=pyhd8ed1ab_1
  - notebook=7.2.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numba=0.60.0=py312hcccf92d_0
  - openjpeg=2.5.2=h3d672ee_0
  - openssl=3.3.2=h2466b09_0
  - optuna=4.0.0=pyhd8ed1ab_0
  - optuna-integration=4.0.0=pyhd8ed1ab_0
  - orc=2.0.2=h784c2ca_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py312h72972c8_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py312h381445a_1
  - pip=24.2=pyh8b19718_1
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - prompt_toolkit=3.0.47=hd8ed1ab_0
  - protobuf=4.25.3=py312h0368a66_1
  - psutil=6.0.0=py312h4389bb4_1
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pyarrow=17.0.0=py312h7e22eef_1
  - pyarrow-core=17.0.0=py312h6a9c419_1_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.12.5=h889d299_0_cpython
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytorch=2.2.0=py3.12_cuda12.1_cudnn8_0
  - pytorch-cuda=12.1=hde6ce7c_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.2=pyhd8ed1ab_0
  - pywin32=306=py312h53d5487_2
  - pywinpty=2.0.13=py312h275cf98_1
  - pyyaml=6.0.2=py312h4389bb4_1
  - pyzmq=26.2.0=py312hd7027bb_2
  - re2=2023.09.01=hd3b24a8_2
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.20.0=py312h2615798_1
  - scikit-learn=1.5.2=py312h816cc57_1
  - scipy=1.14.1=py312h1f4e10d_0
  - send2trash=1.8.3=pyh5737063_0
  - sentry-sdk=2.14.0=pyhd8ed1ab_0
  - setproctitle=1.3.3=py312h4389bb4_1
  - setuptools=73.0.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.2.1=h23299a8_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlalchemy=2.0.35=py312h4389bb4_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.3=py312h1a27103_1
  - stumpy=1.13.0=pyhd8ed1ab_0
  - sympy=1.13.2=pyh04b8f61_3
  - tbb=2021.13.0=hc790b64_0
  - tblib=3.0.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyh5737063_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - tornado=6.4.1=py312h4389bb4_1
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - tsfresh=0.20.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20240906=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2024a=h8827d51_1
  - ucrt=10.0.22621.0=h57928b3_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - vc=14.3=h8a93ad2_21
  - vc14_runtime=14.40.33810=ha82c5b3_21
  - vs2015_runtime=14.40.33810=h3bf8584_21
  - wandb=0.17.3=py312h4389bb4_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - winpty=0.4.3=4
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xyzservices=2024.9.0=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.5=he1f189c_5
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.20.2=pyhd8ed1ab_0
  - zstandard=0.23.0=py312h7606c53_1
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - annotated-types==0.7.0
      - blis==0.7.11
      - catalogue==2.0.10
      - cloudpathlib==0.19.0
      - confection==0.1.5
      - cycler==0.12.1
      - cymem==2.0.8
      - fastai==2.7.17
      - fastcore==1.7.8
      - fastdownload==0.0.7
      - fastprogress==1.0.3
      - fonttools==4.53.1
      - imbalanced-learn==0.12.3
      - kiwisolver==1.4.7
      - langcodes==3.4.0
      - language-data==1.2.0
      - llvmlite==0.43.0
      - marisa-trie==1.2.0
      - markdown-it-py==3.0.0
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - murmurhash==1.0.10
      - numpy==1.26.4
      - preshed==3.0.9
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pyts==0.13.0
      - rich==13.8.1
      - shellingham==1.5.4
      - smart-open==7.0.4
      - spacy==3.7.6
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - thinc==8.2.5
      - torchaudio==2.2.0
      - torchvision==0.17.0
      - tsai==0.3.9
      - typer==0.12.5
      - wasabi==1.1.3
      - weasel==0.4.1
      - wrapt==1.16.0
prefix: C:\Users\egeorge1\.conda\envs\tsai
