name: tabpfn
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _py-xgboost-mutex=2.0=gpu_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - aws-c-auth=0.8.1=hd11252f_0
  - aws-c-cal=0.8.1=h099ea23_3
  - aws-c-common=0.10.6=h2466b09_0
  - aws-c-compression=0.3.0=h099ea23_5
  - aws-c-event-stream=0.5.0=h85d8506_11
  - aws-c-http=0.9.2=h3888f84_4
  - aws-c-io=0.15.3=hc5a9e45_6
  - aws-c-mqtt=0.11.0=h2c94728_12
  - aws-c-s3=0.7.9=h6a47413_1
  - aws-c-sdkutils=0.2.2=h099ea23_0
  - aws-checksums=0.2.2=h099ea23_4
  - aws-crt-cpp=0.29.9=he488853_2
  - aws-sdk-cpp=1.11.489=h7d73209_0
  - blas=1.0=mkl
  - brotli=1.1.0=h2466b09_2
  - brotli-bin=1.1.0=h2466b09_2
  - brotli-python=1.1.0=py312h275cf98_2
  - bzip2=1.0.8=h2466b09_7
  - c-ares=1.34.4=h2466b09_0
  - ca-certificates=2025.1.31=h56e8100_0
  - cairo=1.18.2=h5782bbf_1
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py312h4389bb4_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.1=py312hd5eb7cc_0
  - cpython=3.12.8=py312hd8ed1ab_1
  - cuda-cccl=12.6.77=0
  - cuda-cccl_win-64=12.6.77=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.77=0
  - cuda-opencl-dev=12.6.77=0
  - cuda-profiler-api=12.6.77=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.11=py312h275cf98_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - double-conversion=3.3.0=h63175ca_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - filelock=3.16.1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.3=py312h31fea79_1
  - freetype=2.12.1=hdaf720e_2
  - graphite2=1.3.13=h63175ca_1003
  - h2=4.1.0=pyhd8ed1ab_1
  - harfbuzz=10.1.0=ha6ce084_0
  - hpack=4.0.0=pyhd8ed1ab_1
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.5.0=pyha770c72_1
  - intel-openmp=2025.0.0=h57928b3_1164
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.31.0=pyh7428d3b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.5=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh5737063_1
  - kiwisolver=1.4.7=py312hd5eb7cc_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=h67d730c_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20240722.0=cxx17_h4eb7d71_4
  - libarrow=19.0.1=he9da57d_0_cuda
  - libarrow-acero=19.0.1=h7d8d6a5_0_cuda
  - libarrow-dataset=19.0.1=h7d8d6a5_0_cuda
  - libarrow-substrait=19.0.1=h3dbecdf_0_cuda
  - libblas=3.9.0=1_h8933c1f_netlib
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcblas=3.9.0=8_h719fc58_netlib
  - libclang13=19.1.6=default_ha5278ca_0
  - libcrc32c=1.1.2=h0e60522_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.7.77=0
  - libcurand-dev=10.3.7.77=0
  - libcurl=8.13.0=h88aaa65_0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.23=h9062f6e_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.6.4=he0c23c2_0
  - libffi=3.4.2=h8ffe710_5
  - libglib=2.82.2=h7025463_0
  - libgoogle-cloud=2.35.0=h95c5cb2_0
  - libgoogle-cloud-storage=2.35.0=he5eb982_0
  - libgrpc=1.67.1=h0ac93cb_2
  - libhwloc=2.11.2=default_hc8275d1_1000
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - liblapack=3.9.0=8_h719fc58_netlib
  - liblzma=5.6.3=h2466b09_1
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libparquet=19.0.1=ha850022_0_cuda
  - libpng=1.6.45=had7236b_0
  - libprotobuf=5.28.3=h8309712_1
  - libre2-11=2024.07.02=h4eb7d71_2
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.47.2=h67fdade_0
  - libssh2=1.11.1=he619c9f_0
  - libthrift=0.21.0=hbe90ef8_0
  - libtiff=4.7.0=h797046b_3
  - libutf8proc=2.10.0=hf9b99b7_0
  - libuv=1.49.2=h2466b09_0
  - libwebp=1.5.0=h3b0e114_0
  - libwebp-base=1.5.0=h3b0e114_0
  - libxcb=1.16=h013a479_1
  - libxgboost=2.1.3=cuda126_hb61963e_0
  - libxml2=2.13.5=he286e8c_1
  - libxslt=1.1.39=h3df6e99_0
  - libzlib=1.3.1=h2466b09_2
  - lz4-c=1.10.0=h2466b09_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=3.0.2=py312h31fea79_1
  - matplotlib=3.10.0=py312h2e8e312_0
  - matplotlib-base=3.10.0=py312h90004f6_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.1.0=h6a75c08_48682
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - numpy=2.2.1=py312hf10105a_0
  - openjpeg=2.5.3=h4d64b90_0
  - openssl=3.4.1=ha4e3fda_0
  - orc=2.0.3=haf104fe_2
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py312h72972c8_1
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=h3d7b363_2
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=10.4.0=py312h381445a_1
  - pip=24.3.1=pyh8b19718_2
  - pixman=0.44.2=had0cd8c_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.48=pyha770c72_1
  - psutil=6.1.1=py312h4389bb4_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=h2466b09_4
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=2.1.3=cuda126_pyh206be00_0
  - pyarrow=19.0.1=py312h2e8e312_0
  - pyarrow-core=19.0.1=py312h607bf26_0_cuda
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pyside6=6.8.1=py312h2ee7485_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.12.8=h3f84c4b_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytorch=2.5.1=py3.12_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pywin32=307=py312h275cf98_3
  - pyyaml=6.0.2=py312h4389bb4_1
  - pyzmq=26.2.0=py312hd7027bb_3
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.8.1=h1259614_2
  - re2=2024.07.02=haf4117d_2
  - requests=2.32.3=pyhd8ed1ab_1
  - scikit-learn=1.6.0=py312h816cc57_0
  - scipy=1.15.0=py312h928f2a1_1
  - setuptools=75.6.0=pyhff2d567_1
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h500f7fa_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.4=py312h1a27103_0
  - tbb=2021.13.0=h62715c5_1
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=h5226925_1
  - tornado=6.4.2=py312h4389bb4_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=15.1.0=py312h4389bb4_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - vc=14.3=ha32ba9b_23
  - vc14_runtime=14.42.34433=he29a5d6_23
  - vs2015_runtime=14.42.34433=hdffcdeb_23
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xgboost=2.1.3=cuda126_pyh993ee4f_0
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.5=ha9f60a1_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstandard=0.23.0=py312h7606c53_1
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - cloudpickle==3.1.1
      - einops==0.8.0
      - fsspec==2024.12.0
      - future==1.0.0
      - huggingface-hub==0.27.1
      - hyperopt==0.2.7
      - py4j==0.10.9.9
      - pytz==2024.2
      - seaborn==0.12.2
      - sympy==1.13.1
      - tabpfn==2.0.1
      - tabpfn-extensions==0.0.4
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - tzdata==2024.2
prefix: C:\Users\egeorge1\.conda\envs\tabpfn
