name: tsai
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12.5
  - pytorch=2.2.0
  - pytorch-cuda=12.1
  - scikit-learn=1.5.2
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.14.1
  - statsmodels=0.14.3
  - matplotlib=3.9.2
  - tsfresh=0.20.3
  - stumpy=1.13.0
  - optuna=4.0.0
  - numba=0.60.0
  - pyarrow=17.0.0
  - sqlalchemy=2.0.35
  - tqdm=4.66.5
  - wandb=0.17.3
  - ipykernel=6.29.5
  - jupyterlab=4.2.5
  - pip
  - pip:
      - tsai==0.3.9
      - fastai==2.7.17
      - fastcore==1.7.8
      - pyts==0.13.0
      - spacy==3.7.6
      - torchaudio==2.2.0
      - torchvision==0.17.0
      - imbalanced-learn==0.12.3
      - pydantic==2.9.2
      - rich==13.8.1