name: tabpfn
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12.8
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - scikit-learn=1.6.0
  - numpy=2.2.1
  - pandas=2.2.3
  - xgboost=2.1.3
  - matplotlib=3.10.0
  - pyarrow=19.0.1
  - scipy=1.15.0
  - statsmodels=0.14.4
  - ipykernel=6.29.5
  - pillow=10.4.0
  - pyyaml=6.0.2
  - requests=2.32.3
  - pip
  - pip:
      - tabpfn==2.0.1
      - tabpfn-extensions==0.0.4
      - einops==0.8.0
      - huggingface-hub==0.27.1
      - hyperopt==0.2.7
      - tqdm==4.67.1
      - cloudpickle==3.1.1
      - seaborn==0.12.2
      - fsspec==2024.12.0
      - sympy==1.13.1