name: torch_tabular
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.14
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-lightning=2.1.4
  - pytorch_tabular=1.1.0
  - pytorch-tabnet=4.1.0
  - scikit-learn=1.4.2
  - numpy=1.26.4
  - pandas=2.2.2
  - xgboost=2.1.1
  - scipy=1.13.0
  - statsmodels=0.14.1
  - matplotlib-base=3.8.4
  - seaborn=0.13.2
  - pyarrow=17.0.0
  - tqdm=4.66.4
  - wandb=0.16.5
  - omegaconf=2.3.0
  - category_encoders=2.6.3
  - imbalanced-learn=0.12.3
  - ipykernel=6.29.3
  - pip
  - pip:
      - pytorch-optimizer==2.12.0
      - torchaudio==0.13.1
      - torchvision==0.14.1